# Generated by Django 5.1.4 on 2024-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_drivetrain_choices_car_drivetrain'),
        ('users', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_cars',
            field=models.ManyToManyField(blank=True, related_name='favorite_by', to='cars.car'),
        ),
    ]
