version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped  # Add this for automatic restart
    healthcheck: # Add health check
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - DJANGO_SETTINGS_MODULE=drivolution.settings.production
      - POSTGRES_HOST=db
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: unless-stopped  # Add this
    healthcheck: # Add health check
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - web

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck: # Add health check
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data: