# Generated by Django 5.1.4 on 2024-12-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='DRIVETRAIN_CHOICES',
            new_name='drivetrain',
        ),
    ]
