# Generated by Django 5.1.4 on 2024-12-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_drivetrain_choices_car_drivetrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
